# Generated by Django 4.1.2 on 2022-10-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(max_length=260, null=True, verbose_name='Email'),
        ),
    ]
